import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const questions = [
  // History Questions (10%)
  {
    question: "من هو القائد العربي الذي فتح الأندلس؟",
    answer: "طارق",
    answerFirstLetter: "ط",
    difficulty: "متوسط",
    category: "تاريخ",
    hint: "سمي مضيق باسمه",
    answered: true,
  },
  {
    question: "ما هي المعركة التي انتصر فيها صلاح الدين على الصليبيين؟",
    answer: "حطين",
    answerFirstLetter: "ح",
    difficulty: "متوسط",
    category: "تاريخ",
    hint: "وقعت في فلسطين",
    answered: true,
  },
  {
    question: "من هو مؤسس الدولة العباسية؟",
    answer: "أبو العباس",
    answerFirstLetter: "أ",
    difficulty: "صعب",
    category: "تاريخ",
    hint: "لقب بالسفاح",
    answered: true,
  },
  {
    question: "من هو مؤسس مدينة بغداد؟",
    answer: "المنصور",
    answerFirstLetter: "ا",
    difficulty: "صعب",
    category: "تاريخ",
    hint: "ثاني خلفاء بني العباس",
    answered: true,
  },
  {
    question: "ما هي المعركة التي انتصر فيها خالد بن الوليد على الفرس؟",
    answer: "القادسية",
    answerFirstLetter: "ا",
    difficulty: "متوسط",
    category: "تاريخ",
    hint: "وقعت في العراق",
    answered: true,
  },

  // Science Questions (10%)
  {
    question: "ما هو المركب الأساسي في الكيمياء العضوية؟",
    answer: "كربون",
    answerFirstLetter: "ك",
    difficulty: "سهل",
    category: "علوم",
    hint: "أساس الحياة على الأرض",
    answered: true,
  },
  {
    question: "ما هو الغاز الذي تحتاجه النباتات للقيام بعملية البناء الضوئي؟",
    answer: "ثاني",
    answerFirstLetter: "ث",
    difficulty: "سهل",
    category: "علوم",
    hint: "غاز ثاني أكسيد الكربون",
    answered: true,
  },
  {
    question: "ما هو العنصر الذي يسبب الصدأ في الحديد؟",
    answer: "أكسجين",
    answerFirstLetter: "ا",
    difficulty: "متوسط",
    category: "علوم",
    hint: "غاز موجود في الهواء",
    answered: true,
  },
  {
    question: "ما هو العنصر الذي يسبب اللون الأخضر في أوراق النباتات؟",
    answer: "كلوروفيل",
    answerFirstLetter: "ك",
    difficulty: "متوسط",
    category: "علوم",
    hint: "صبغة خضراء",
    answered: true,
  },
  {
    question: "ما هو العنصر الذي يسبب الحموضة في الليمون؟",
    answer: "حمض",
    answerFirstLetter: "ح",
    difficulty: "سهل",
    category: "علوم",
    hint: "حمض الستريك",
    answered: true,
  },

  // Sports Questions (5%)
  {
    question: "من هو هداف المنتخب السعودي في كأس العالم 1994؟",
    answer: "سعيد",
    answerFirstLetter: "س",
    difficulty: "صعب",
    category: "رياضة",
    hint: "سجل هدف الفوز على بلجيكا",
    answered: true,
  },
  {
    question: "من هو حارس مرمى المنتخب السعودي في كأس العالم 1994؟",
    answer: "الدعيع",
    answerFirstLetter: "ا",
    difficulty: "متوسط",
    category: "رياضة",
    hint: "لقب بالصقر",
    answered: true,
  },
  {
    question:
      "من هو اللاعب السعودي الذي سجل هدف الفوز على الأرجنتين في كأس العالم 2022؟",
    answer: "سالم الدوسري",
    answerFirstLetter: "س",
    difficulty: "سهل",
    category: "رياضة",
    hint: "هدف تاريخي",
    answered: true,
  },
  {
    question:
      "من هو اللاعب السعودي الذي سجل هدف الفوز على مصر في كأس العالم 2018؟",
    answer: "الدوسري",
    answerFirstLetter: "ا",
    difficulty: "متوسط",
    category: "رياضة",
    hint: "هدف في الدقيقة الأخيرة",
    answered: true,
  },
  {
    question:
      "من هو اللاعب السعودي الذي سجل هدف الفوز على اليابان في كأس آسيا 2023؟",
    answer: "الدوسري",
    answerFirstLetter: "ا",
    difficulty: "سهل",
    category: "رياضة",
    hint: "هدف في المباراة النهائية",
    answered: true,
  },

  // Geography Questions (20%)
  {
    question: "ما هي عاصمة آيسلندا؟",
    answer: "ريكيافيك",
    answerFirstLetter: "ر",
    difficulty: "صعب",
    category: "جغرافيا",
    hint: "أقصى شمال عاصمة في العالم",
    answered: true,
  },
  {
    question: "ما هي عاصمة اليابان؟",
    answer: "طوكيو",
    answerFirstLetter: "ط",
    difficulty: "سهل",
    category: "جغرافيا",
    hint: "أكبر مدينة في العالم",
    answered: true,
  },
  {
    question: "ما هي عاصمة البرازيل؟",
    answer: "برازيليا",
    answerFirstLetter: "ب",
    difficulty: "متوسط",
    category: "جغرافيا",
    hint: "مدينة حديثة البناء",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في العالم؟",
    answer: "النيل",
    answerFirstLetter: "ن",
    difficulty: "سهل",
    category: "جغرافيا",
    hint: "يمر بمصر",
    answered: true,
  },
  {
    question: "ما هو أعلى جبل في العالم؟",
    answer: "إفرست",
    answerFirstLetter: "ا",
    difficulty: "سهل",
    category: "جغرافيا",
    hint: "يقع في جبال الهيمالايا",
    answered: true,
  },
  {
    question: "ما هي أكبر غابة في العالم؟",
    answer: "الأمازون",
    answerFirstLetter: "ا",
    difficulty: "سهل",
    category: "جغرافيا",
    hint: "تقع في أمريكا الجنوبية",
    answered: true,
  },
  {
    question: "ما هي عاصمة النرويج؟",
    answer: "أوسلو",
    answerFirstLetter: "ا",
    difficulty: "متوسط",
    category: "جغرافيا",
    hint: "عاصمة دولة إسكندنافية",
    answered: true,
  },
  {
    question: "ما هي عاصمة فنلندا؟",
    answer: "هلسنكي",
    answerFirstLetter: "ه",
    difficulty: "صعب",
    category: "جغرافيا",
    hint: "عاصمة دولة إسكندنافية",
    answered: true,
  },
  {
    question: "ما هي عاصمة الدنمارك؟",
    answer: "كوبنهاجن",
    answerFirstLetter: "ك",
    difficulty: "صعب",
    category: "جغرافيا",
    hint: "عاصمة دولة إسكندنافية",
    answered: true,
  },

  // Literature Questions (5%)
  {
    question: "من هو مؤلف رواية 'مئة عام من العزلة'؟",
    answer: "غابرييل",
    answerFirstLetter: "غ",
    difficulty: "صعب",
    category: "أدب",
    hint: "كاتب كولومبي",
    answered: true,
  },
  {
    question: "من هو مؤلف رواية '1984'؟",
    answer: "أورويل",
    answerFirstLetter: "ا",
    difficulty: "متوسط",
    category: "أدب",
    hint: "كاتب بريطاني",
    answered: true,
  },
  {
    question: "من هو مؤلف رواية 'البؤساء'؟",
    answer: "هوغو",
    answerFirstLetter: "ه",
    difficulty: "متوسط",
    category: "أدب",
    hint: "كاتب فرنسي",
    answered: true,
  },
  {
    question: "من هو مؤلف رواية 'الجريمة والعقاب'؟",
    answer: "دوستويفسكي",
    answerFirstLetter: "د",
    difficulty: "صعب",
    category: "أدب",
    hint: "كاتب روسي",
    answered: true,
  },
  {
    question: "من هو مؤلف رواية 'الحرب والسلام'؟",
    answer: "تولستوي",
    answerFirstLetter: "ت",
    difficulty: "صعب",
    category: "أدب",
    hint: "كاتب روسي",
    answered: true,
  },

  // Religion Questions (20%)
  {
    question: "ما هي السورة التي لقبت بقلب القرآن؟",
    answer: "يس",
    answerFirstLetter: "ي",
    difficulty: "متوسط",
    category: "دين",
    hint: "رقمها 36",
    answered: true,
  },
  {
    question: "من هو الصحابي الذي لقب بأسد الله؟",
    answer: "حمزة",
    answerFirstLetter: "ح",
    difficulty: "سهل",
    category: "دين",
    hint: "عم النبي",
    answered: true,
  },
  {
    question: "ما هي السورة التي لقبت بأم الكتاب؟",
    answer: "الفاتحة",
    answerFirstLetter: "ا",
    difficulty: "سهل",
    category: "دين",
    hint: "أول سورة في القرآن",
    answered: true,
  },
  {
    question: "من هو الصحابي الذي لقب بذي النورين؟",
    answer: "عثمان",
    answerFirstLetter: "ع",
    difficulty: "صعب",
    category: "دين",
    hint: "ثالث الخلفاء الراشدين",
    answered: true,
  },
  {
    question: "ما هي السورة التي لقبت بعروس القرآن؟",
    answer: "الرحمن",
    answerFirstLetter: "ا",
    difficulty: "صعب",
    category: "دين",
    hint: "تكرر فيها 'فبأي آلاء ربكما تكذبان'",
    answered: true,
  },
  {
    question: "من هو الصحابي الذي لقب بترجمان القرآن؟",
    answer: "عبدالله",
    answerFirstLetter: "ع",
    difficulty: "صعب",
    category: "دين",
    hint: "ابن عباس",
    answered: true,
  },
  {
    question: "ما هي السورة التي لقبت بقلب القرآن؟",
    answer: "يس",
    answerFirstLetter: "ي",
    difficulty: "متوسط",
    category: "دين",
    hint: "رقمها 36",
    answered: true,
  },
  {
    question: "من هو الصحابي الذي لقب بأمين الأمة؟",
    answer: "أبو عبيدة",
    answerFirstLetter: "ا",
    difficulty: "صعب",
    category: "دين",
    hint: "من العشرة المبشرين بالجنة",
    answered: true,
  },
  {
    question: "ما هي السورة التي لقبت بسورة التوديع؟",
    answer: "النصر",
    answerFirstLetter: "ن",
    difficulty: "صعب",
    category: "دين",
    hint: "آخر سورة نزلت",
    answered: true,
  },

  // General Knowledge Questions (30%)
  {
    question: "ما معنى كلمة 'ضيم'؟",
    answer: "ظلم",
    answerFirstLetter: "ظ",
    difficulty: "متوسط",
    category: "معلومات عامة",
    hint: "معنى من معاني الظلم",
    answered: true,
  },
  {
    question: "ما هو الحيوان الذي يسمى ملك الغابة؟",
    answer: "أسد",
    answerFirstLetter: "ا",
    difficulty: "سهل",
    category: "معلومات عامة",
    hint: "حيوان مفترس",
    answered: true,
  },
  {
    question: "ما هو أكبر عضو في جسم الإنسان؟",
    answer: "جلد",
    answerFirstLetter: "ج",
    difficulty: "سهل",
    category: "معلومات عامة",
    hint: "يغطي الجسم كله",
    answered: true,
  },
  {
    question: "ما هو أسرع حيوان بري في العالم؟",
    answer: "فهد",
    answerFirstLetter: "ف",
    difficulty: "سهل",
    category: "معلومات عامة",
    hint: "من فصيلة القطط",
    answered: true,
  },
  {
    question: "ما هو أطول حيوان في العالم؟",
    answer: "دودة",
    answerFirstLetter: "د",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "تعيش في المحيط",
    answered: true,
  },
  {
    question: "ما هو أذكى حيوان في العالم؟",
    answer: "دلفين",
    answerFirstLetter: "د",
    difficulty: "متوسط",
    category: "معلومات عامة",
    hint: "يعيش في البحر",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في أوروبا؟",
    answer: "فولغا",
    answerFirstLetter: "ف",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "يمر بروسيا",
    answered: true,
  },
  {
    question: "ما هو أكبر محيط في العالم؟",
    answer: "هادئ",
    answerFirstLetter: "ه",
    difficulty: "سهل",
    category: "معلومات عامة",
    hint: "يغطي مساحة كبيرة من الأرض",
    answered: true,
  },
  {
    question: "ما هو أطول جبل في السعودية؟",
    answer: "طويق",
    answerFirstLetter: "ط",
    difficulty: "متوسط",
    category: "معلومات عامة",
    hint: "يمثل همة السعوديين",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في آسيا؟",
    answer: "يانغتسي",
    answerFirstLetter: "ي",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "يمر بالصين",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في أفريقيا؟",
    answer: "كونغو",
    answerFirstLetter: "ك",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "يمر بجمهورية الكونغو",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في أمريكا الجنوبية؟",
    answer: "الأمازون",
    answerFirstLetter: "ا",
    difficulty: "سهل",
    category: "معلومات عامة",
    hint: "يمر بالبرازيل",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في أمريكا الشمالية؟",
    answer: "المسيسيبي",
    answerFirstLetter: "ا",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "يمر بالولايات المتحدة",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في أستراليا؟",
    answer: "موراي",
    answerFirstLetter: "م",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "يمر بجنوب أستراليا",
    answered: true,
  },
  {
    question: "ما هو أطول نهر في نيوزيلندا؟",
    answer: "وايكاتو",
    answerFirstLetter: "و",
    difficulty: "صعب",
    category: "معلومات عامة",
    hint: "يمر بجزيرة الشمال",
    answered: true,
  },
];

async function main() {
  console.log(`Start seeding ...`);

  for (const question of questions) {
    const result = await prisma.question.create({
      data: question,
    });
    console.log(`Created question with id: ${result.id}`);
  }

  console.log(`Seeding finished.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
